config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :posts, only: [:index, :show, :new, :create, :destroy, :edit, :update ]

  resources :users, only: [:index, :show, :new, :create]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
  has_many :comments

  validates :content, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments

  validates :title, :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts
  has_many :comments

  validates :username, :password, :email, presence: true
  validates :username, :email, uniqueness: true
  validates :password, length: { in: 6..20 }
  validates :email, format: /.+@.+\.{1}.{2,}/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
   http_basic_authenticate_with name: "dhh", password: "secret", except: :index

   def index
     render plain: "Everyone can see me!"
   end

   def edit
     render plain: "I'm only accessible if you know the password"
   end

  # def index
  #   @posts = Post.all
  # end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to posts_path
    else
      render :new
    end
  end

  # def edit
  #   @post = Post.find(params[:id])
  # end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to post_path(@post)
    else
      render :edit
    end
  end

  def destroy

  end

  private

  def post_params
    params.require(:post).permit(:title, :content)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  private

  def user_params
    params.require('user').permit(:username, :password, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsReddit</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <div class="row">
        <div class="col-md-6 offset-md-3 py-3">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= simple_form_for(post) do |f| %>
  <%= f.input :title %>
  <%= f.input :content, :input_html => {rows: 10} %>
  <%= f.submit class: 'btn btn-outline-success w-100' %>
<% end %>

app/views/posts/edit.html.erb
<%= render 'posts/form', post: @post %>

<%= link_to "return to post", post_path(@post), class: 'btn btn-outline-success'%>
<%= link_to "return to top", posts_path, class: 'btn btn-outline-danger'%>

app/views/posts/index.html.erb
<h1>Posts#index</h1>
<p><%= link_to "Create a new post", new_post_path, class: 'btn btn-outline-warning w-100' %></p>
<p><%= link_to "Sign up", new_user_path, class: 'btn btn-outline-primary w-100' %></p>
<p><%= link_to "See all users", users_path, class: 'btn btn-outline-info w-100' %></p>
<p><%= link_to "Log in", users_path, class: 'btn btn-outline-info w-100' %></p>


<ol>
  <% @posts.reverse.each do |post| %>
    <li>
      <h4> <%= link_to post.title, post_path(post) %> </h4>
      <small> <%= link_to "(#{post.user.username})", user_path(post.user) %> </small>
    </li>
  <% end %>
</ol>

app/views/posts/new.html.erb
<%= render 'posts/form', post: @post %>

<%= link_to 'Return to top', posts_path, class: 'w-100 btn btn-outline-secondary my-3' %>

app/views/posts/show.html.erb
<h1>Title: <%= @post.title %></h1>
<h3>Content: <%= @post.content %></h3>
<p>User: <%= @post.user.username %></p>

<%= link_to "edit post", edit_post_path %>
<%= link_to "Return to top", posts_path %>

app/views/users/_form.html.erb
<%= simple_form_for(user) do |f| %>
  <%= f.input :username %>
  <%= f.input :password %>
  <%= f.input :email %>

  <%= f.submit class: 'btn btn-outline-success w-100' %>
<% end %>

app/views/users/index.html.erb
<h1>All Users</h1>

<ul>
  <% @users.each do |user| %>
    <li><%= link_to user.username, user_path(user) %></li>
  <% end %>
</ul>

app/views/users/new.html.erb
<%= render 'users/form', user: @user %>

<%= link_to 'Return to top', users_path, class: 'w-100 btn btn-outline-secondary my-3' %>

app/views/users/show.html.erb
<h1>Username: <%= @user.username %></h1>
<p>Password: <%= @user.password %></p>
<p>Email: <%= @user.email %></p>

<%= link_to "return to top", posts_path %>